-- Fixed Athena query for contact_record_qs_cr_dataset view
CREATE OR REPLACE VIEW connect-datalake-local.contact_record_qs_cr_dataset AS
SELECT instance_id,
	aws_account_id,
	contact_id,
	initial_contact_id,
	previous_contact_id,
	related_contact_id,
	next_contact_id,
	channel,
	initiation_method,
	-- Fix: Direct timestamp casting for string timestamps
	CAST(initiation_timestamp AS timestamp) AS initiation_timestamp,
	CAST(connected_to_system_timestamp AS timestamp) AS connected_to_system_timestamp,
	CAST(last_update_timestamp AS timestamp) AS last_update_timestamp,
	CAST(scheduled_timestamp AS timestamp) AS scheduled_timestamp,
	CAST(transfer_completed_timestamp AS timestamp) AS transfer_completed_timestamp,
	CAST(disconnect_timestamp AS timestamp) AS disconnect_timestamp,
	disconnect_reason,
	queue_duration_ms,
	CAST(queue_dequeue_timestamp AS timestamp) AS queue_dequeue_timestamp,
	CAST(queue_enqueue_timestamp AS timestamp) AS queue_enqueue_timestamp,
	queue_name,
	queue_arn,
	queue_id,
	agent_connection_attempts,
	CAST(agent_connected_to_agent_timestamp AS timestamp) AS agent_connected_to_agent_timestamp,
	agent_interaction_duration_ms,
	agent_customer_hold_duration_ms,
	agent_number_of_holds,
	agent_longest_hold_duration_ms,
	CAST(agent_after_contact_work_start_timestamp AS timestamp) AS agent_after_contact_work_start_timestamp,
	CAST(agent_after_contact_work_end_timestamp AS timestamp) AS agent_after_contact_work_end_timestamp,
	agent_after_contact_work_duration_ms,
	attributes,
	agent_username,
	agent_arn,
	agent_id,
	instance_arn,
	agent_hierarchy_groups_level_1_name,
	agent_hierarchy_groups_level_1_arn,
	agent_hierarchy_groups_level_1_id,
	agent_hierarchy_groups_level_2_name,
	agent_hierarchy_groups_level_2_arn,
	agent_hierarchy_groups_level_2_id,
	agent_hierarchy_groups_level_3_name,
	agent_hierarchy_groups_level_3_arn,
	agent_hierarchy_groups_level_3_id,
	agent_hierarchy_groups_level_4_name,
	agent_hierarchy_groups_level_4_arn,
	agent_hierarchy_groups_level_4_id,
	agent_hierarchy_groups_level_5_name,
	agent_hierarchy_groups_level_5_arn,
	agent_hierarchy_groups_level_5_id,
	agent_routing_profile_name,
	agent_routing_profile_arn,
	agent_routing_profile_id,
	aws_contact_trace_record_format_version,
	campaign_Id,
	customer_endpoint_type,
	customer_endpoint_address,
	transferred_endpoint_type,
	transferred_endpoint_address,
	system_endpoint_type,
	system_endpoint_address,
	recording_deletion_reason,
	recording_location,
	recording_status,
	recording_type,
	answering_machine_detection_Status,
	voice_id_result_authentication_result,
	voice_id_result_fraud_detection_watch_list_id,
	voice_id_result_speaker_id,
	voice_id_result_fraud_detection_result,
	voice_id_result_fraud_detection_fraudster_Id,
	external_third_party_interaction_duration_ms,
	voice_id_result_authentication_minimum_speech_ms,
	voice_id_result_authentication_score,
	voice_id_result_authentication_score_threshold,
	voice_id_result_fraud_detection_risk_score_known_fraudster,
	voice_id_result_fraud_detection_risk_score_synthetic_speech,
	voice_id_result_fraud_detection_risk_score_voice_spoofing,
	voice_id_result_fraud_detection_score_threshold,
	agent_pause_duration_ms,
	voice_id_result_speaker_enrolled,
	voice_id_result_speaker_opted_out,
	media_streams_items,
	voice_id_result_fraud_detection_reasons_items,
	tags_references_items,
	contact_details,
	contact_evaluations,
	references,
	agent_state_transitions,
	recordings,
	CAST(data_lake_last_processed_timestamp AS timestamp) AS data_lake_last_processed_timestamp,
	agent_device_platform_name,
	agent_device_platform_version,
	agent_device_operating_system,
	agent_capabilities_video,
	customer_device_platform_name,
	customer_device_platform_version,
	customer_device_operating_system,
	customer_capabilities_video,
	disconnect_details_potential_disconnect_issue,
	disconnect_details_telemetry_inferred_reason,
	task_template_arn,
	task_template_name,
	CAST(last_resumed_timestamp AS timestamp) AS last_resumed_timestamp,
	CAST(last_paused_timestamp AS timestamp) AS last_paused_timestamp,
	CAST(customer_voice_activity_greeting_start_timestamp AS timestamp) AS customer_voice_activity_greeting_start_timestamp,
	CAST(customer_voice_activity_greeting_end_timestamp AS timestamp) AS customer_voice_activity_greeting_end_timestamp,
	total_pause_duration_ms,
	total_pause_count,
	contact_routing_queue_priority,
	contact_routing_queue_time_adjustment_ms,
	quality_metrics_agent_reported_issue,
	quality_metrics_agent_audio,
	quality_metrics_customer_audio,
	segment_attributes,
	-- Duration calculations in minutes
	(CAST(queue_duration_ms AS decimal(20, 6)) / 1000) / 60 AS queue_duration_min,
	(CAST(agent_interaction_duration_ms AS decimal(20, 6)) / 1000) / 60 AS agent_interaction_duration_min,
	(CAST(agent_customer_hold_duration_ms AS decimal(20, 6)) / 1000) / 60 AS agent_customer_hold_duration_min,
	(CAST(agent_longest_hold_duration_ms AS decimal(20, 6)) / 1000) / 60 AS agent_longest_hold_duration_min,
	(CAST(agent_after_contact_work_duration_ms AS decimal(20, 6)) / 1000) / 60 AS agent_after_contact_work_duration_min,
	(CAST(external_third_party_interaction_duration_ms AS decimal(20, 6)) / 1000) / 60 AS external_third_party_interaction_duration_min,
	(CAST(voice_id_result_authentication_minimum_speech_ms AS decimal(20, 6)) / 1000) / 60 AS voice_id_result_authentication_minimum_speech_min,
	(CAST(agent_pause_duration_ms AS decimal(20, 6)) / 1000) / 60 AS agent_pause_duration_min,
	(CAST(total_pause_duration_ms AS decimal(20, 6)) / 1000) / 60 AS total_pause_duration_min,
	(CAST(contact_routing_queue_time_adjustment_ms AS decimal(20, 6)) / 1000) / 60 AS contact_routing_queue_time_adjustment_min,
	-- Duration calculations using date_diff
	date_diff('millisecond', 
		CAST(agent_connected_to_agent_timestamp AS timestamp),
		CAST(disconnect_timestamp AS timestamp)
	) AS agent_connected_to_agent_duration_ms,
	date_diff('millisecond',
		CAST(initiation_timestamp AS timestamp),
		CAST(disconnect_timestamp AS timestamp)
	) AS total_duration_ms,
	(CAST(date_diff('millisecond', 
		CAST(agent_connected_to_agent_timestamp AS timestamp),
		CAST(disconnect_timestamp AS timestamp)
	) AS decimal(20, 6)) / 1000) / 60 AS agent_connected_to_agent_duration_min,
	(CAST(date_diff('millisecond',
		CAST(initiation_timestamp AS timestamp),
		CAST(disconnect_timestamp AS timestamp)
	) AS decimal(20, 6)) / 1000) / 60 AS total_duration_min
FROM contact_record;