default_agent: strands_claude_getting_started
agents:
  strands_claude_getting_started:
    name: strands_claude_getting_started
    entrypoint: /Users/sodhani/Documents/repo/amazon-bedrock-agentcore-samples/01-tutorials/06-AgentCore-observability/01-Agentcore-runtime-hosted/strands_claude.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::461312420708:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-8556fc4504
      execution_role_auto_create: false
      account: '461312420708'
      region: us-west-2
      ecr_repository: 461312420708.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-strands_claude_getting_started
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: strands_claude_getting_started-vOiuP7AfS6
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:461312420708:runtime/strands_claude_getting_started-vOiuP7AfS6
      agent_session_id: a4c0132d-2154-4750-8bdd-75076eabdec9
    codebuild:
      project_name: bedrock-agentcore-strands_claude_getting_started-builder
      execution_role: arn:aws:iam::461312420708:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-8556fc4504
      source_bucket: bedrock-agentcore-codebuild-sources-461312420708-us-west-2
    authorizer_configuration: null
    oauth_configuration: null
